# Name of workflow
name: Admin Deploy workflow

# When workflow is triggered
on:
  pull_request:
    branches:
      - dev
  push:
    branches: [dev, main]

# Jobs to carry out
jobs:
  deploy:

    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:

      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      # Install NodeJS
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}